//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public Nullable<int> InventaireID { get; set; }
        public Nullable<int> ArmeJoueurID { get; set; }
        public Nullable<int> ArmureJoueurID { get; set; }
        public Nullable<int> PotionJoueurID { get; set; }
    
        public virtual ArmesJoueur ArmesJoueur { get; set; }
        public virtual ArmuresJoueur ArmuresJoueur { get; set; }
        public virtual Inventaire Inventaire { get; set; }
        public virtual PotionsJoueur PotionsJoueur { get; set; }
    }
}
